version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: currency-api
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data: