version: "3.9"

services:
  app:
    image: varshil44/currency-api:latest
    container_name: currency-api
    ports:
      - "${PORT}:3000"
    environment:
      - PORT=${PORT}
      - REDIS_URL=${REDIS_URL}
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6380:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data:
